package Calculator;


/**
* Calculator/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* domingo 26 de febrero de 2023 20H43' CET
*/

public interface CalcOperations 
{
  int calculate (int opcode, int op1, int op2);
  void exit ();
} // interface CalcOperations
